version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
#    restart: on-failure
    ports:
      - "9090:9090" #http
      - "5050:5050" #jmx
    environment:
      - CLIENT_HOST=server
      - JAEGER_HOST=jaeger
      - JAEGER_ENABLE=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - HAZELCAST_HOST=hazelcast
      - HAZELCAST_PORT=5701
      - HAZELCAST_CLUSTERNAME=dev
      - CACHE_EXPIRATIONS_PERSON=1s
      - XMS=50M
      - XMX=8G
    deploy:
      resources:
        limits:
          memory: 8g
    depends_on:
      redis:
        condition: service_healthy
      server:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
#    restart: on-failure
    ports:
      - "9191:9191" #http
      - "5151:5151" #jmx
    environment:
      - JAEGER_HOST=jaeger
      - JAEGER_ENABLE=true
      - XMS=50M
      - XMX=2G

  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a password ping | grep PONG" ]
      # docker inspect --format "{{json .State.Health }}" containerId  | jq
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  hazelcast:
    image: hazelcast/hazelcast
    ports:
      - "5701:5701"

  redis-commander:
    image: rediscommander/redis-commander:latest
    profiles: ["frontend"]
    restart: always
    environment:
      - REDIS_HOSTS=redis
      - REDIS_HOST=redis
      - REDIS_PORT=redis:6379
      - REDIS_PASSWORD=password
    ports:
      - "8081:8081"

  hazelcast-management-center:
    image: hazelcast/management-center
    profiles: ["frontend"]
    ports:
      - "8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast

  jaeger:
    image: jaegertracing/all-in-one:latest
    profiles: ["frontend"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

volumes:
  cache:
    driver: local