management:
  endpoints:
    web:
      exposure:
        include: health,httptrace

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  port: '9191'
opentracing:
  jaeger:
    service-name: server
    enabled: ${JAEGER_ENABLE:false}
    udp-sender:
      host: ${JAEGER_HOST:localhost}
