management:
  endpoints:
    web:
      exposure:
        include: health,httptrace

feign:
  client:
    config:
      person-client:
        loggerLevel: headers

person:
  client:
    host: http://${CLIENT_HOST:localhost}:9191
opentracing:
  jaeger:
    service-name: client
    enabled: ${JAEGER_ENABLE:false}
    udp-sender:
      host: ${JAEGER_HOST:localhost}
server:
  port: '9090'
logging:
  level:
    com:
      example:
        demo:
          client: DEBUG
    org:
      springframework:
        cache: trace

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      enabled: false

cache:
  ttl: 5m
  redisHost: ${REDIS_HOST:localhost}
  redisPort: ${REDIS_PORT:6379}
  redisPassword: ${REDIS_PASSWORD:password}
  hazelCastHost: ${HAZELCAST_HOST:localhost}
  hazelCastPort: ${HAZELCAST_PORT:5701}
  hazelCastClusterName: ${HAZELCAST_CLUSTERNAME:dev}
  expirations:
    person: 5m
